### ISSUE TITLE
支持tun模式吗

### ISSUE THREAD

**Issue by kwucheuwkzbAks** [csj8520/clash_for_flutter#2]

**Comment by AndyYQ1111** [comment]
能支持tun模式吗

**Comment by csj8520** [comment]
支持

**Comment by AndyYQ1111** [comment]
我运行起来后，设置好yaml ，但是并不能开启服务。
<img width="1130" alt="image" src="https://github.com/csj8520/clash_for_flutter/assets/12421636/8aeac8ec-7094-4bbf-8dc8-e4dc3baed2a3">

**Comment by AndyYQ1111** [comment]
clash 核心下载下来后需要放在哪里

**Comment by csj8520** [comment]
@Yueqingshan 先运行命令 `make init-amd64` 下载依赖，脚本会自动处理，具体可查看 `Makefile`

**Comment by AndyYQ1111** [comment]
> @Yueqingshan 先运行命令 `make init-amd64` 下载依赖，脚本会自动处理，具体可查看 `Makefile`

谢谢，可以正常工作了.

**Comment by AndyYQ1111** [comment]
开启服务后，好像并没有开启tun 模式，因为 终端 `curl https://www.google.com` 并不能连接

**Comment by AndyYQ1111** [comment]
开启系统代理才能正常访问google

**Comment by csj8520** [comment]
@Yueqingshan 
有可能是配置的问题，可以参考下我的
还要注意 `clash` 内核需要在管理员权限下才可以开启 `tun` 模式，
MacOS 需要程序设置DNS，也可以查看此处是否设置成功
https://github.com/csj8520/clash_for_flutter/blob/d97fca44c4628f4ffa03196ce211c3458eceb245/lib/controllers/service.dart#L204C7-L204C7
```yaml
dns:
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enable: true
  ipv6: false
  # enhanced-mode: redir-host
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:53
  fake-ip-filter:
    - "*.lan"
    - "microsoft.com"
    - "*.microsoft.com"
    - "+.msftconnecttest.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29

tun:
  enable: true
  # stack: system
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  auto-route: true # auto set global route for Windows
  # It is recommended to use `interface-name`
  auto-detect-interface: true # auto detect interface, conflict with `interface-name`

```
